module.exports = [
  {title: 'Introduction to React Native',
   remaining: 12,
   presenter: 'Brent Vatne',
   presenterImageUrl: 'https://s3.amazonaws.com/corecore-events/image/38/medium/13e1189.jpg?1430072432',
   bio: 'Brent is a Senior Developer at Madriska Inc, a contributor to React Native and an instructor and TA at CodeCore.',
   description: 'React Native enables you to build world-class application experiences on native platforms using a consistent developer experience based on JavaScript and React. The focus of React Native is on developer efficiency across all the platforms you care about — learn once, write anywhere. Facebook uses React Native in multiple production apps and will continue investing in React Native.',
   date: 'Monday, Apr 27, 2015',
   time: '12:00 PM - 01:00 PM'},

  {title: 'Leadership, culture, strategy & execution in a tech start-up',
   presenter: 'LUKE AULIN',
   remaining: 3,
   bio: 'Luke Aulin is the founder of RTown.ca',
   description: '',
   date: 'Tuesday, Apr 28, 2015',
   time: '12:00 PM - 01:00 PM'},

  {title: 'How to not be a terrible programmer',
   presenter: 'CLARKE BRUNSDON',
   remaining: 25,
   description: '',
   bio: 'Clarke Brunsdon from FreeRunningTechnologies.com',
   date: 'Wednesday, Apr 29, 2015',
   time: '12:00 PM - 01:00 PM'},

  {title: 'Machine Learning',
   presenter: 'CHARLES ILIYA KREMPEAUX',
   bio: 'Charles Iliya Krempeaux from ea.ca',
   description: '',
   remaining: 8,
   date: 'Thursday, Apr 30, 2015',
   time: '12:00 PM - 01:00 PM'},

  {title: "Essentials every developer should know about 'International'",
   presenter: 'JIM DELAHUNT',
   remaining: 39,
   bio: 'Jim DeLaHunt from jdlh.com/en/',
   description: '',
   date: 'Friday, Apr 31, 2015',
   time: '12:00 PM - 01:00 PM'}
]
