module.exports = [
  {title: 'Introduction to React Native',
   remaining: 12,
   presenter: 'Brent Vatne',
   presenterImageUrl: 'https://s3.amazonaws.com/corecore-events/image/38/medium/13e1189.jpg?1430072432',
   splashImageUrl: 'https://facebook.github.io/react/img/logo_og.png',
   bio: 'Brent is a Senior Developer at Madriska Inc, a contributor to React Native and an instructor and TA at CodeCore.',
   description: 'React Native enables you to build world-class application experiences on native platforms using a consistent developer experience based on JavaScript and React. The focus of React Native is on developer efficiency across all the platforms you care about — learn once, write anywhere. Facebook uses React Native in multiple production apps and will continue investing in React Native.',
   date: 'Monday, Apr 27, 2015',
   time: '12:00 PM - 01:00 PM'},

  {title: 'Leadership, culture, strategy & execution in a tech start-up',
   presenter: 'LUKE AULIN',
   remaining: 3,
   splashImageUrl: 'http://www.gew.co/sites/www.unleashingideas.org/files/images/gew2012_cbc_hkh.jpg',
   presenterImageUrl: 'https://s3.amazonaws.com/corecore-events/image/39/medium/2879e4d.jpg?1429133975',
   bio: 'Luke Aulin is the founder of RTown.ca',
   description: "Strategic management involves the formulation and implementation of the major goals and initiatives taken by a company's top management on behalf of owners, based on consideration of resources and an assessment of the internal and external environments in which the organization competes.",
   date: 'Tuesday, Apr 28, 2015',
   time: '12:00 PM - 01:00 PM'},

  {title: 'How to not be a terrible programmer',
   splashImageUrl: 'http://www.georgiancard.ge/gcweb/images/stories/267781.jpg',
   presenterImageUrl: 'https://s3.amazonaws.com/corecore-events/image/40/medium/0d584e1.jpg?1429133921',
   presenter: 'CLARKE BRUNSDON',
   remaining: 25,
   description: "Strategic management provides overall direction to the enterprise and involves specifying the organization's objectives, developing policies and plans designed to achieve these objectives, and then allocating resources to implement the plans. Academics and practicing managers have developed numerous models and frameworks to assist in strategic decision making in the context of complex environments and competitive dynamics. Strategic management is not static in nature; the models often include a feedback loop to monitor execution and inform the next round of planning.",
   bio: 'Clarke Brunsdon from FreeRunningTechnologies.com',
   date: 'Wednesday, Apr 29, 2015',
   time: '12:00 PM - 01:00 PM'},

  {title: 'Machine Learning',
   presenter: 'CHARLES ILIYA KREMPEAUX',
   splashImageUrl: 'http://www.gew.co/sites/www.unleashingideas.org/files/images/gew2012_cbc_hkh.jpg',
   bio: 'Charles Iliya Krempeaux from ea.ca',
   presenterImageUrl: 'https://s3.amazonaws.com/corecore-events/image/40/medium/0d584e1.jpg?1429133921',
   description: "Strategic management involves the formulation and implementation of the major goals and initiatives taken by a company's top management on behalf of owners, based on consideration of resources and an assessment of the internal and external environments in which the organization competes.",
   remaining: 8,
   date: 'Thursday, Apr 30, 2015',
   time: '12:00 PM - 01:00 PM'},

  {title: "Essentials every developer should know about 'International'",
   presenterImageUrl: 'https://s3.amazonaws.com/corecore-events/image/41/medium/0ba7790.jpg?1429133888',
   splashImageUrl: 'http://www.georgiancard.ge/gcweb/images/stories/267781.jpg',
   presenter: 'JIM DELAHUNT',
   remaining: 39,
   bio: 'Jim DeLaHunt from jdlh.com/en/',
   description: "Strategic management involves the formulation and implementation of the major goals and initiatives taken by a company's top management on behalf of owners, based on consideration of resources and an assessment of the internal and external environments in which the organization competes.",
   date: 'Friday, Apr 31, 2015',
   time: '12:00 PM - 01:00 PM'}
]
